#!/bin/bash

for cmd in jq curl top df nproc; do
  if [ "$(command -v $cmd)" == "" ]; then
    echo "$cmd command not found"
    exit 1
  fi
done

top=$(top -b -w 512 -n 1)
df=$(df -B1 | grep -v tmpfs)
cores=$(nproc --all)
uptime=$(cat /proc/uptime)

data=$(jq -n \
  --arg top "$top" \
  --arg df "$df" \
  --arg cores "$cores" \
  --arg uptime "$uptime" \
  '{"top": $top, "df": $df, "cores": $cores, "uptime": $uptime}')

curl -s -S -k -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: Bearer :TOKEN" \
  -d "$data" \
  :URL
